language: rust

rust:
  - 1.31.0
  - stable
  - beta
  - nightly

script: cargo test

matrix:
  include:
    - rust: nightly
      name: Minimal versions
      before_script:
        - cargo -Z minimal-versions generate-lockfile
      script:
        - cargo check --locked
